### ISSUE TITLE
Data array is not reactive

### ISSUE THREAD

**Issue by tnfAngel** [Dimchykus/use-data-paginate#1]
When the array changes (for example, an element is removed), the module ignores it and uses the initial version

**Comment by tnfAngel** [comment]
I would love for this to work, because it really is a very useful module and above all it saves you a lot of time

**Comment by Dimchykus** [comment]
Thanks for reporting the issue, I will do my best to fix it asap

**Comment by Dimchykus** [comment]
Hi, I have deployed fix. Pls check it out. Sorry for the delay.

**Comment by tnfAngel** [comment]
LGTM!
